import type { CSSProperties } from "react";

/** Co-located styles for CiTab (installations + run history + Fail-CI-on). */
export const s = {
  wrap: { display: "flex", flexDirection: "column", height: "100%", minHeight: 0 } satisfies CSSProperties,
  header: { padding: "20px 24px 16px", borderBottom: "1px solid var(--border)" } satisfies CSSProperties,
  titleRow: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  } satisfies CSSProperties,
  h2: { fontSize: 16, fontWeight: 700 } satisfies CSSProperties,
  subtitle: { fontSize: 13, color: "var(--text-muted)", marginTop: 2 } satisfies CSSProperties,
  titleActions: { display: "flex", alignItems: "center", gap: 8, flexShrink: 0 } satisfies CSSProperties,
  failOn: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  failOnLabel: { fontSize: 12, color: "var(--text-muted)", whiteSpace: "nowrap" } satisfies CSSProperties,
  list: { flex: 1, overflow: "auto", padding: "16px 24px" } satisfies CSSProperties,
  sectionTitle: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: 0.4,
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  installs: { display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  installRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 8,
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
  } satisfies CSSProperties,
  repo: { fontFamily: "var(--font-mono)", fontSize: 13, flex: 1, minWidth: 0, overflowWrap: "anywhere" } satisfies CSSProperties,
  version: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  status: { fontSize: 12, color: "var(--text-secondary)", minWidth: 90, textAlign: "right" } satisfies CSSProperties,
  runs: { display: "flex", flexDirection: "column", gap: 4 } satisfies CSSProperties,
  runRow: {
    display: "grid",
    gridTemplateColumns: "70px 110px 1fr 1fr 1fr 60px",
    alignItems: "center",
    gap: 10,
    padding: "8px 12px",
    borderRadius: 8,
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
  } satisfies CSSProperties,
  pr: { fontFamily: "var(--font-mono)", fontSize: 13 } satisfies CSSProperties,
  muted: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  hint: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
