import type { CiExportInput } from '@devdigest/shared';
import {
  ARTIFACT_NAME,
  DEFAULT_TRIGGERS,
  RESULT_FILE,
  RUNNER_ENTRY_PATH,
  VALID_TRIGGERS,
} from './constants.js';

/**
 * Pure generator for `.github/workflows/devdigest-review.yml` (AC-1/AC-4).
 * No I/O — data in, YAML string out.
 *
 * The review mechanism is a plain `run:` step invoking the bundled runner
 * (`node .devdigest/runner/index.js`) — deliberately NOT a
 * `uses: devdigest/review-action@…` marketplace action (AC-4), so the whole
 * pipeline is self-contained in the exported bundle with no external action
 * to trust/pin. Secrets are referenced by NAME only via `${{ secrets.* }}`
 * (AC-24/AC-31) — no value is ever embedded.
 */
export interface WorkflowInput {
  triggers: readonly string[];
  postAs: CiExportInput['post_as'];
}

export function workflowYaml(input: WorkflowInput): string {
  const chosen = input.triggers.filter((t) => VALID_TRIGGERS.has(t));
  const types = (chosen.length > 0 ? chosen : DEFAULT_TRIGGERS).map((t) => `      - ${t}`).join('\n');

  return `# Generated by DevDigest — Export to CI. Edits are preserved on re-export.
name: DevDigest Review
on:
  pull_request:
    types:
${types}

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Run DevDigest review
        env:
          OPENROUTER_API_KEY: \${{ secrets.OPENROUTER_API_KEY }}
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: \${{ github.repository }}
          PR_NUMBER: \${{ github.event.pull_request.number }}
          DEVDIGEST_POST_AS: ${input.postAs}
        run: node ${RUNNER_ENTRY_PATH}

      - name: Upload DevDigest result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${ARTIFACT_NAME}
          path: ${RESULT_FILE}
          if-no-files-found: ignore
`;
}
