import type { CSSProperties } from "react";

export const s = {
  body: { padding: 24, display: "flex", flexDirection: "column", gap: 18 } satisfies CSSProperties,
  stepBar: { padding: "18px 24px 0" } satisfies CSSProperties,
  targetGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
  } satisfies CSSProperties,
  targetOption: (active: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "12px 14px",
    borderRadius: 8,
    border: `1px solid ${active ? "var(--accent)" : "var(--border-strong)"}`,
    background: active ? "var(--bg-hover)" : "var(--bg-elevated)",
    cursor: "pointer",
  }),
  targetLabel: { fontSize: 14, fontWeight: 600 } satisfies CSSProperties,
  targetDesc: { fontSize: 12, color: "var(--text-muted)", marginTop: 2 } satisfies CSSProperties,
  recommended: {
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--ok)",
    marginLeft: 6,
  } satisfies CSSProperties,
  sectionTitle: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  fileList: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  fileRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 10px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    fontSize: 13,
  } satisfies CSSProperties,
  filePath: { flex: 1, fontFamily: "var(--font-mono, monospace)" } satisfies CSSProperties,
  workflowBox: {
    width: "100%",
    minHeight: 220,
    resize: "vertical",
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12.5,
    lineHeight: 1.5,
    outline: "none",
  } satisfies CSSProperties,
  triggerRow: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  secretRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 10px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    fontSize: 13,
  } satisfies CSSProperties,
  secretStatus: { marginLeft: "auto", fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  installOption: (active: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "14px",
    borderRadius: 8,
    border: `1px solid ${active ? "var(--accent)" : "var(--border-strong)"}`,
    background: active ? "var(--bg-hover)" : "var(--bg-elevated)",
    cursor: "pointer",
  }),
  footer: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)", lineHeight: 1.5 } satisfies CSSProperties,
  error: { fontSize: 13, color: "var(--crit)" } satisfies CSSProperties,
} as const;
