import type { CSSProperties } from "react";

export const s = {
  wrap: {
    display: "flex",
    flexDirection: "column",
    gap: 0,
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    overflow: "hidden",
  } satisfies CSSProperties,
  body: {
    display: "grid",
    gridTemplateColumns: "minmax(220px, 320px) 1fr",
    gap: 0,
    minHeight: 240,
  } satisfies CSSProperties,
  summary: {
    fontSize: 13,
    color: "var(--text-secondary)",
    padding: "10px 16px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    padding: 10,
    borderRight: "1px solid var(--border)",
    overflow: "auto",
  } satisfies CSSProperties,
  findingRow: (active: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "8px 10px",
    borderRadius: 6,
    border: "none",
    textAlign: "left",
    cursor: "pointer",
    background: active ? "var(--bg-hover)" : "transparent",
  }),
  findingTitle: {
    fontSize: 13,
    color: "var(--text-primary)",
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  findingLoc: { fontSize: 11, color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  empty: { fontSize: 13, color: "var(--text-muted)", padding: "8px 10px" } satisfies CSSProperties,
  detail: { padding: 16, overflow: "auto" } satisfies CSSProperties,
  detailBody: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  detailHeader: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  detailTitle: { fontSize: 15, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  detailMeta: { display: "flex", alignItems: "center", gap: 12 } satisfies CSSProperties,
  fileLoc: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  prose: { fontSize: 14, lineHeight: 1.6, color: "var(--text-secondary)" } satisfies CSSProperties,
  suggestionWrap: { marginTop: 4 } satisfies CSSProperties,
  suggestionLabel: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.05em",
    color: "var(--text-muted)",
    marginBottom: 8,
    textTransform: "uppercase",
  } satisfies CSSProperties,
} as const;
